package com.ibm.migration.service;

import java.util.ArrayList;
import java.util.List;

import org.jboss.logging.Logger;

import com.ibm.migration.model.MigrationResult;

import jakarta.enterprise.context.ApplicationScoped;

/**
 * Service for converting PostgreSQL queries to DB2
 */
@ApplicationScoped
public class QueryConversionService {

    private static final Logger LOG = Logger.getLogger(QueryConversionService.class);

    public MigrationResult convertQuery(String querySQL) {
        LOG.infof("Converting PostgreSQL query to DB2");
        
        List<String> warnings = new ArrayList<>();
        List<String> recommendations = new ArrayList<>();
        
        String converted = querySQL;
        
        // String concatenation: || → CONCAT
        if (converted.contains("||")) {
            converted = converted.replaceAll("(\\w+)\\s*\\|\\|\\s*(\\w+)", "CONCAT($1, $2)");
            warnings.add("String concatenation (||) converted to CONCAT function");
        }
        
        // Case-insensitive search: ILIKE → UPPER(column) LIKE UPPER(value)
        if (converted.contains("ILIKE")) {
            converted = converted.replaceAll("(\\w+)\\s+ILIKE\\s+'([^']+)'", "UPPER($1) LIKE UPPER('$2')");
            warnings.add("ILIKE converted to UPPER() LIKE UPPER() - less efficient");
            recommendations.add("Consider creating function-based index on UPPER(column)");
        }
        
        // Boolean values: TRUE/FALSE → 1/0
        if (converted.contains("TRUE") || converted.contains("FALSE")) {
            converted = converted.replaceAll("\\bTRUE\\b", "1");
            converted = converted.replaceAll("\\bFALSE\\b", "0");
            warnings.add("Boolean TRUE/FALSE converted to 1/0");
        }
        
        // Pagination: LIMIT/OFFSET → FETCH FIRST/OFFSET
        if (converted.contains("LIMIT")) {
            converted = converted.replaceAll("LIMIT\\s+(\\d+)\\s+OFFSET\\s+(\\d+)", "OFFSET $2 ROWS FETCH FIRST $1 ROWS ONLY");
            converted = converted.replaceAll("LIMIT\\s+(\\d+)", "FETCH FIRST $1 ROWS ONLY");
            warnings.add("LIMIT/OFFSET converted to FETCH FIRST/OFFSET ROWS");
        }
        
        // Date/time functions
        if (converted.contains("NOW()")) {
            converted = converted.replace("NOW()", "CURRENT TIMESTAMP");
            warnings.add("NOW() converted to CURRENT TIMESTAMP");
        }
        
        if (converted.contains("CURRENT_DATE")) {
            converted = converted.replace("CURRENT_DATE", "CURRENT DATE");
            warnings.add("CURRENT_DATE converted to CURRENT DATE");
        }
        
        // Array operations
        if (converted.contains("ANY(") || converted.contains("ARRAY[")) {
            warnings.add("Array operations detected - DB2 has limited array support");
            recommendations.add("Consider redesigning queries to avoid arrays or use temporary tables");
        }
        
        // JSON operations
        if (converted.contains("->") || converted.contains("->>")) {
            warnings.add("JSON operators detected - not supported in DB2");
            recommendations.add("Store JSON as CLOB and parse in application layer");
        }
        
        // Generate Spring Data JPA adjustments
        String jpaAdjustments = generateJpaAdjustments(converted);
        recommendations.add("Review Spring Data JPA repository methods");
        recommendations.add("Test all queries with actual DB2 database");
        
        return new MigrationResult(
            converted,
            jpaAdjustments,
            warnings,
            recommendations
        );
    }

    private String generateJpaAdjustments(String query) {
        return String.format("""
            // Spring Data JPA Adjustments for DB2
            // Generated by Java to DB2 Migration Assistant
            
            // Original Query (PostgreSQL):
            // %s
            
            // Recommended JPA Configuration:
            // spring.jpa.database-platform=org.hibernate.dialect.DB2Dialect
            // spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
            
            // For boolean fields, use Integer type:
            // @Column(name = "active")
            // private Integer active; // 0 = false, 1 = true
            
            // For CLOB fields:
            // @Lob
            // @Column(columnDefinition = "CLOB")
            // private String description;
            
            """, query);
    }
}

// Made with Bob
