package com.ibm.migration.service;

import java.util.ArrayList;
import java.util.List;

import org.jboss.logging.Logger;

import com.ibm.migration.model.MigrationResult;

import jakarta.enterprise.context.ApplicationScoped;

/**
 * Service for generating migration test suites
 */
@ApplicationScoped
public class TestGenerationService {

    private static final Logger LOG = Logger.getLogger(TestGenerationService.class);

    public MigrationResult generateTests(String entityCode) {
        LOG.infof("Generating test suite for entity");
        
        List<String> warnings = new ArrayList<>();
        List<String> recommendations = new ArrayList<>();
        
        String testClass = generateTestClass(entityCode);
        String testConfig = generateTestConfiguration();
        
        recommendations.add("Run tests against actual DB2 database or H2 in DB2 mode");
        recommendations.add("Add integration tests for complex queries");
        recommendations.add("Test data type conversions thoroughly");
        recommendations.add("Verify boolean field handling (0/1 instead of true/false)");
        
        return new MigrationResult(
            testClass,
            testConfig,
            warnings,
            recommendations
        );
    }

    private String generateTestClass(String entityCode) {
        // Extract entity name (simplified)
        String entityName = "Entity";
        if (entityCode.contains("class ")) {
            int start = entityCode.indexOf("class ") + 6;
            int end = entityCode.indexOf(" ", start);
            if (end == -1) end = entityCode.indexOf("{", start);
            if (end > start) {
                entityName = entityCode.substring(start, end).trim();
            }
        }
        
        return String.format("""
            package com.example.migration.test;
            
            import org.junit.jupiter.api.Test;
            import org.springframework.beans.factory.annotation.Autowired;
            import org.springframework.boot.test.context.SpringBootTest;
            import org.springframework.transaction.annotation.Transactional;
            import static org.junit.jupiter.api.Assertions.*;
            
            /**
             * Integration tests for %s migration to DB2
             * Generated by Java to DB2 Migration Assistant
             */
            @SpringBootTest
            @Transactional
            class %sDb2MigrationTest {
            
                @Autowired
                private %sRepository repository;
            
                @Test
                void testEntityPersistence() {
                    // Test basic CRUD operations
                    %s entity = new %s();
                    // Set entity properties
                    
                    %s saved = repository.save(entity);
                    assertNotNull(saved.getId());
                    
                    %s found = repository.findById(saved.getId()).orElse(null);
                    assertNotNull(found);
                }
            
                @Test
                void testIdentityColumnGeneration() {
                    // Test that IDENTITY columns work correctly (was SERIAL in PostgreSQL)
                    %s entity1 = new %s();
                    %s entity2 = new %s();
                    
                    %s saved1 = repository.save(entity1);
                    %s saved2 = repository.save(entity2);
                    
                    assertNotNull(saved1.getId());
                    assertNotNull(saved2.getId());
                    assertNotEquals(saved1.getId(), saved2.getId());
                }
            
                @Test
                void testBooleanFieldConversion() {
                    // Test that boolean fields work as SMALLINT (0/1)
                    %s entity = new %s();
                    // entity.setActive(1); // 1 = true, 0 = false
                    
                    %s saved = repository.save(entity);
                    // assertEquals(1, saved.getActive());
                }
            
                @Test
                void testClobFieldHandling() {
                    // Test that TEXT fields work as CLOB
                    %s entity = new %s();
                    String largeText = "Large text content...".repeat(1000);
                    // entity.setDescription(largeText);
                    
                    %s saved = repository.save(entity);
                    // assertNotNull(saved.getDescription());
                    // assertTrue(saved.getDescription().length() > 1000);
                }
            
                @Test
                void testQueryPagination() {
                    // Test that pagination works with FETCH FIRST (was LIMIT in PostgreSQL)
                    // Create test data
                    for (int i = 0; i < 20; i++) {
                        repository.save(new %s());
                    }
                    
                    // Test pagination
                    // Page<%s> page = repository.findAll(PageRequest.of(0, 10));
                    // assertEquals(10, page.getContent().size());
                }
            
                @Test
                void testCaseInsensitiveSearch() {
                    // Test case-insensitive search (was ILIKE in PostgreSQL)
                    %s entity = new %s();
                    // entity.setName("Test Name");
                    repository.save(entity);
                    
                    // List<%s> results = repository.findByNameContainingIgnoreCase("test");
                    // assertFalse(results.isEmpty());
                }
            }
            """, entityName, entityName, entityName, entityName, entityName, entityName,
                 entityName, entityName, entityName, entityName, entityName, entityName,
                 entityName, entityName, entityName, entityName, entityName, entityName,
                 entityName, entityName, entityName, entityName, entityName, entityName);
    }

    private String generateTestConfiguration() {
        return """
            # Test Configuration for DB2 Migration
            # src/test/resources/application-test.properties
            
            # Option 1: Use H2 in DB2 compatibility mode
            spring.datasource.url=jdbc:h2:mem:testdb;MODE=DB2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
            spring.datasource.driver-class-name=org.h2.Driver
            spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
            
            # Option 2: Use Testcontainers with actual DB2
            # spring.datasource.url=jdbc:tc:db2:11.5.9.0:///testdb
            # spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
            
            # JPA Configuration
            spring.jpa.hibernate.ddl-auto=create-drop
            spring.jpa.show-sql=true
            spring.jpa.properties.hibernate.format_sql=true
            
            # Flyway (disable for tests or use test migrations)
            spring.flyway.enabled=false
            
            # Logging
            logging.level.org.hibernate.SQL=DEBUG
            logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
            
            # Add to pom.xml for testing:
            # <dependency>
            #     <groupId>com.h2database</groupId>
            #     <artifactId>h2</artifactId>
            #     <scope>test</scope>
            # </dependency>
            # 
            # <!-- OR use Testcontainers -->
            # <dependency>
            #     <groupId>org.testcontainers</groupId>
            #     <artifactId>db2</artifactId>
            #     <scope>test</scope>
            # </dependency>
            """;
    }
}

// Made with Bob
